# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "ahci"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/mapper/luks-3ba29b52-605a-4405-a6c3-1cf20d810b16";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-3ba29b52-605a-4405-a6c3-1cf20d810b16".device =
    "/dev/disk/by-uuid/3ba29b52-605a-4405-a6c3-1cf20d810b16";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/D751-B601";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [
    { device = "/dev/mapper/luks-7d7b6fbb-f87b-454a-a613-74e38b810ae9"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
